### ISSUE TITLE
Arch User Repository?

### ISSUE THREAD

**Issue by evdunbar** [encounter/objdiff#103]
I've written some PKGBUILDs to allow me to easily build the project. Would there be interest in putting them in the AUR and/or the README? No need to upload them if I'm the only one to ever use them though.

Any comments on how they are packaged as well? I currently have `objdiff` and `objdiff-cli` in one package together, but they could be separated out.

**Comment by encounter** [comment]
I see no harm in having it in the AUR, I just generally point people to the prebuilt binaries for ease of use. If you do publish it, would you add me (https://aur.archlinux.org/account/encounter) as a co-maintainer?

I think having both binaries packaged together is fine!

**Comment by evdunbar** [comment]
I will definitely add you then!

What's your opinion on `objdiff` vs. `objdiff-bin` vs. `objdiff-git`? I see that you resolved #104 which I discovered when trying to test the `PKGBUILD` for `objdiff`, but the build will still fail until there's a new release. Should I use the git tag instead of the archive tarball until then (assuming you think just a regular package makes the most sense)?

**Comment by encounter** [comment]
Personally, I think having both `objdiff-bin` and `objdiff` would be ideal. I tend to release pretty frequently, so `-git` may not be all that useful in the grand scheme of things. I'll be publishing v2.0.0 momentarily.

**Comment by encounter** [comment]
Just published v2.1.0 and tested/updated the AUR packages. All seems well. Thanks!
