### ISSUE TITLE
Can't build when not in a git repo (from source archives)

### ISSUE THREAD

**Issue by evdunbar** [encounter/objdiff#104]
You cannot build from the latest source tarball. Dependency `vergen` causes the build to fail because it is not in a git repository. This is because `vergen`'s builder is set to fail on error in `objdiff-gui/build.rs`.

This can be fixed by removing the method call `.fail_on_error()`, but I didn't want to create a PR yet because that's probably called for a reason.

**Comment by encounter** [comment]
I removed `fail_on_error` in bcc5871cd8bae7f1b3b015be45373136c28add47. Though there's also the `VERGEN_IDEMPOENT` environment variable which may be of use: https://docs.rs/vergen/9.0.0/vergen/#environment-variables

**Comment by roblabla** [comment]
FWIW objdiff-cli has the same problem, but doesn't use vergen - it runs `git` directly.

I also made an objdiff package for NixOS (https://github.com/NixOS/nixpkgs/pull/335478), and had to patch out the build.rs for it to build properly.

**Comment by encounter** [comment]
I'll just rip out the vergen/git stuff in the next release, it's not providing much value anyway
