### ISSUE TITLE
Allow comparing functions with differing names

### ISSUE THREAD

**Issue by RootCubed** [encounter/objdiff#117]
In cases where symbols maps are not or only partially available, it is not easily possible to compare the target against the base function:

![image](https://github.com/user-attachments/assets/c92abced-f485-41eb-82e4-a27ead022972)

It would be nice if, when clicking on a function that doesn't have a corresponding symbol, you could select the function to compare against. (Ideally this could be saved in the objdiff.json for persistence)

Even better, objdiff could maybe even try to automatically find the corresponding symbol by looking at the function order.

**Comment by elijah-thomas774** [comment]
This would be especially good for when you need to often change parameters to see the effect!
