### ISSUE TITLE
Feature request: make the diff ignore differences between hardcoded pointers and symbols

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [encounter/objdiff#131]

**Comment by encounter** [comment]
I made improvements here, could you try the latest build? https://github.com/encounter/objdiff/actions/runs/11621539005

If it still doesn’t work, could you provide example objects?

**Comment by H-A-M-G-E-R** [comment]
![image](https://github.com/user-attachments/assets/3f4f4ebd-4e6e-446c-a165-712698f25ed9)
the dif needs to ignore them

**Comment by encounter** [comment]
Could you provide the objects?

**Comment by H-A-M-G-E-R** [comment]
[event.zip](https://github.com/user-attachments/files/17607981/event.zip)

**Comment by encounter** [comment]
It does work on the latest build. I forgot to mention to enable the “Relax relocation diffs” option under “Diff Settings”
