### ISSUE TITLE
Set preset when creating a scratch for decomp.me

### ISSUE THREAD

**Issue by 1superchip** [encounter/objdiff#133]
The preset isn't set currently when creating a scratch. This causes scratches to be unlinked from the project they are a part of.

Projects will have to get the preset id from decomp.me to set in the config. If the id isn't set, a scratch can be uploaded without the preset field.

<https://github.com/decompme/decomp.me/blob/36edf529ca2b165fa162cee6cede6ef5dd2150a0/backend/coreapp/views/scratch.py#L282>

**Comment by encounter** [comment]
Added to dtk-template: https://github.com/encounter/dtk-template/commit/065fc7b71541d93e18d410b0f7423b6f8a4fa18f

Will be released in objdiff v2.4.0
