### ISSUE TITLE
View that shows which line of source asm corresponds to the line in decompiled source

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [encounter/objdiff#134]
like in decomp.me, makes decomping big functions easier

**Comment by encounter** [comment]
objdiff does show source line numbers if the object was compiled with debug information (DWARFv1 .line and DWARFv2+). Does your platform use a different line number format?

**Comment by H-A-M-G-E-R** [comment]
[waver.zip](https://github.com/user-attachments/files/17636099/waver.zip)
umm.. it's not working although the flags are `-O2 -mthumb-interwork -fhex-asm -ffix-debug-line`?

**Comment by encounter** [comment]
Looks like you’re missing `-g3`, referencing the flags from a decomp.me scratch.

**Comment by H-A-M-G-E-R** [comment]
however adding those settings would make the project nonmatching
`.align 2, 0 @ dont insert nops` is added to the end by makefile, and it's in the debug section making them useless unless debug info is turned off
the project: https://github.com/H-A-M-G-E-R/mf

**Comment by encounter** [comment]
Maybe an agbcc change could make it emit debug info without changing codegen? Or you could set up extra Makefile rules for objects built with debug info. Regardless, this is out of objdiff’s scope at this point.

**Comment by H-A-M-G-E-R** [comment]
solution: seperate makefile commands
