### ISSUE TITLE
[BUG] "Incomplete" Filter doesn't do anything

### ISSUE THREAD

**Issue by DeathHound6** [encounter/objdiff#144]
Complete file "__init_cpp_exceptions". Shown with Relax Relocation Diffs off
![image](https://github.com/user-attachments/assets/3bc5d4b4-d39f-498d-aa42-383183ae7649)

Incomplete filter is off and complete file is shown
![image](https://github.com/user-attachments/assets/57d6786c-aec5-4865-b4e3-8e8f7cbeaa03)

Incomplete filter is on and the file is still shown
![image](https://github.com/user-attachments/assets/5450188a-c019-46cb-902e-91591956544f)

It seems like the filter doesn't actually do anything

Hidden filter works as expected
All files in my project are Diffable, so I cannot test this one easily

**Comment by encounter** [comment]
Once you mark one of the objects complete (or “Matching”), this will filter them out.

**Comment by DeathHound6** [comment]
I have no idea how I forgot about that
For some reason just assumed objdiff would know when it's matched

Thanks
