### ISSUE TITLE
Wildcards in "units" field in objdiff.json

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [encounter/objdiff#147]
example:
```
{
  "build_base": true,
  "build_target": false,
  "watch_patterns": [
    "*.c",
    "*.h"
  ],
  "units": [
    {
      "name": "sprites_AI/*",
      "target_path": "build/asm/sprites_AI/*.o",
      "base_path": "build/src/sprites_AI/*.o",
      "metadata": {}
    }
  ]
}

```

**Comment by encounter** [comment]
`objdiff.json` is intended to be fully enumerated. I recommend writing a script to generate the objdiff config in order to implement project-specific logic like this.

**Comment by H-A-M-G-E-R** [comment]
i made a script to create objdiff.json for mf: https://github.com/H-A-M-G-E-R/mf/blob/main/tools/objdiffConfig.py
