### ISSUE TITLE
Setting to scale text size

### ISSUE THREAD

**Issue by mattbruv** [encounter/objdiff#21]
It would be easier on my eyes if I could scale the text to a size of my liking, perhaps with a setting slider.

**Comment by encounter** [comment]
This was implemented in v0.2.0, though a little hidden. File -> Show Config will open up the settings window:

![image](https://user-images.githubusercontent.com/549122/206598531-8d177d08-cb9a-4acf-9d73-b1b77e25fd0d.png)
