### ISSUE TITLE
Stack offset highlighting doesn't work for different instructions

### ISSUE THREAD

**Issue by LagoLunatic** [encounter/objdiff#32]
If you click on a particular stack offset, objdiff highlights other instances of that offset for similar instructions (e.g. stfs/lfs) as expected:
![image](https://github.com/encounter/objdiff/assets/19174152/cdd4fed5-f774-4625-acdb-090f46b30551)

However, it misses instances that are for a completely different instruction (e.g. addi doesn't highlight lfs and lfs doesn't highlight addi):
![image](https://github.com/encounter/objdiff/assets/19174152/6c3ca824-675c-4cf2-935b-e0a30b28ccd6)
![image](https://github.com/encounter/objdiff/assets/19174152/fee1f527-e807-403c-bc0d-4b15e0d2d252)

Example function: dLib_checkActorInCircle
Versions tested on: 0.5.2, 0.6.0

**Comment by encounter** [comment]
Thanks for the report! I fixed this by comparing signed immediates and register offsets and considering them equivalent. If there are other instances where the highlight doesn't pick up things that it semantically should, please let me know.
