### ISSUE TITLE
Immediates don't highlight each other between load and compare instructions

### ISSUE THREAD

**Issue by LagoLunatic** [encounter/objdiff#33]
![image](https://github.com/encounter/objdiff/assets/19174152/d51906a8-2ecd-4ada-aa31-f2def77de9fe)
![image](https://github.com/encounter/objdiff/assets/19174152/ed56ebc0-b14a-452d-9c9a-4b8def4d611c)

Example function: setBeastItemEmpty__21dSv_player_bag_item_cFUc

**Comment by Antidote** [comment]
I'm not sure what the issue is here, if you want to see where the immediate is being used/compared you should select the register it's loaded into, *not* the immediate, I don't think this is a bug.
