### ISSUE TITLE
Check extab/extabindex size equivalency

### ISSUE THREAD

**Issue by vabold** [encounter/objdiff#36]
The current behavior appears to ignore extab/extabindex when determining if an object is complete. An example is seen here: 
![image](https://github.com/encounter/objdiff/assets/86704247/41fc428e-cfb0-4952-a89b-74e22428080a)

The rest of the file is generated correctly, and objdiff marks it complete: 
![image](https://github.com/encounter/objdiff/assets/86704247/737823ab-a5ba-453c-b209-03423ae0b61b)

The mismatched size leads to a mismatch in overall section size, so the expected behavior would be to mark the object as incomplete.

**Comment by encounter** [comment]
The "complete" flag in objdiff is pulled from the build script. If it's marked as "Matching" there, it'll show up green in objdiff. It's merely a way to visualize which files are linked, rather than diffing each file and somehow determining equivalency.
