### ISSUE TITLE
CI build or local builds fail to run on headless Windows 2022 RDP server.

### ISSUE THREAD

**Issue by OmniBlade** [encounter/objdiff#56]
Builds taken from the CI or built locally fail with the following:

2024-04-18T13:58:26.417705Z ERROR eframe::native::run: Exiting because of error: WGPU error: Failed to create wgpu adapter, no suitable adapter found. during event Resumed
thread 'main' panicked at objdiff-gui\src/main.rs:66:6:
Failed to run eframe application: Wgpu(NoSuitableAdapterFound)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\release\objdiff.exe` (exit code: 101)

Running the stable release build works correctly as expected.

**Comment by encounter** [comment]
The latest builds now are built with DirectX 12 support and a graphics configurator, could you try again and see if that helps?

**Comment by OmniBlade** [comment]
Latest CI build seems to work fine for me in the remote desktop use case.

**Comment by OmniBlade** [comment]
Can also confirm that a local clone of the master branch also now works.

**Comment by encounter** [comment]
Great!
