### ISSUE TITLE
[Bug] GUI version is crashing with WSL(2)

### ISSUE THREAD

**Issue by Yanis42** [encounter/objdiff#66]
currently the case for the latest release, steps to reproduce:
- have a project on WSL
- start objdiff GUI on Windows
- select the project's folder
- objdiff will freeze and eventually crash, it seems there's nothing else I can provide to help

I tried the CLI version to see if there was a similar issue and it worked, and the GUI version worked when I moved the project's folder to my Windows desktop

**Comment by TakaRikka** [comment]
also getting this with tp decomp. crashes immediately upon selecting the project folder, which is under WSL2

**Comment by AetiasHax** [comment]
It seems to work when running from source, so the release build might be broken

**Comment by AetiasHax** [comment]
I looked into this a bit further, it seems the crash is caused when trying to use `notify` to watch a directory for file changes. The [Windows implementation in `notify`](https://github.com/notify-rs/notify/blob/3df0f65152c8585cfb29d231c880b86b9164dcfd/notify/src/windows.rs#L301) does this by calling the Win32 API function [ReadDirectoryChangesW](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-readdirectorychangesw) which presumably doesn't work with `\\wsl.localhost\<distro>` paths.

As for why `notify` crashes... it's got something to do with their unsafe error handling when `ReadDirectoryChangesW` returns false. Disabling LTO (`lto = "off"`) fixes the crash, but the watching functionality is still not there.

Unfortunately, `notify` only builds for one target OS at a time, so it seems we can't access both the Linux and Windows implementations in a single build. The best we can do is disable directory watching when opening WSL projects, I think.

**Comment by Yanis42** [comment]
> which presumably doesn't work with \\wsl.localhost\<distro> paths

I also tried using ``Z:/path/to/project`` instead of ``\\wsl.localhost/distro/path/to/project`` and it was crashing too
