### ISSUE TITLE
Filter Sybmols doesnt work for all sections.

### ISSUE THREAD

**Issue by SquareMan** [encounter/objdiff#80]
Possibly only works for .text, not sure.

This example file is zEntPlayer from bfbb. If I try to filter for `sHackStuckDir` from .bss the search fails.

![image](https://github.com/encounter/objdiff/assets/3579314/6b414cd3-dd0a-4feb-9b95-041aee5d6a00)

![image](https://github.com/encounter/objdiff/assets/3579314/eec8d931-79e5-4925-8223-2cb2b866d245)

Filtering for symbols in .text works fine however.

**Comment by LagoLunatic** [comment]
This bug specifically seems to happen for capital letters. When I just tested (version: v2.0.0-alpha.5), lowercase letters, numbers, and symbols like `@` and `$` can be filtered on in data sections, but uppercase letters never match the filter regardless of whether you type them in as uppercase or lowercase.

**Comment by SquareMan** [comment]
Additionally .comm symbols don't filter at all (seen in the screenshot)

**Comment by LagoLunatic** [comment]
Also, while the capital filtering bug doesn't affect C++ functions, it does seem to affect `extern "C"` functions. e.g.:
```cpp
extern "C" {
void Test() {
    
}
}
```
