### ISSUE TITLE
objdiff-cli diff: allow writing diff to a file.

### ISSUE THREAD

**Issue by roblabla** [encounter/objdiff#96]
It'd be awesome to use `objdiff-cli diff` as part of a CI pipeline to be able to display the diff between an implementation and the original.

I currently do this hackily by diffing some asm dumps manually (See https://github.com/happyhavoc/th06/actions/runs/10192215949#user-content-enemy____updateeffects), but this runs into all kind of issues that objdiff already solves.

Unfortunately, `objdiff-cli diff` seems to only support TUI operation, and cannot just output the diff to standard output.

**Comment by encounter** [comment]
This was implemented in v2.0.0-beta.4. The diff structures are defined with [protobuf](https://github.com/encounter/objdiff/blob/main/objdiff-core/protos/diff.proto), and the diff command accepts [options for output and format](https://github.com/encounter/objdiff/blob/68606dfdcbe06d2b5bb1a3ab0c4add4c378719d2/objdiff-cli/src/cmd/diff.rs#L61-L66). Let me know if this fits your needs!

**Comment by roblabla** [comment]
One small question: My script will currently treat differing relocations as being a diff, while objdiff does not. I'm not sure how I'm supposed to detect this and treat them as a match.

**Comment by encounter** [comment]
It _should_, unless you pass --relax-reloc-diffs. So that's odd. Do you have an example?

**Comment by roblabla** [comment]
Ah, that fixed it. I had missed the `--relax-reloc-diffs` flag. With this, everything's working great!
